# Generated by Django 2.2.12 on 2020-06-25 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20200625_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
