# Generated by Django 2.2.12 on 2020-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_auto_20200625_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='hashtag',
            field=models.CharField(default='#photos', max_length=200),
        ),
    ]
